# Change these first
owner: symapex # Your GitHub organization or username, where this repository lives
repo: upsite # The name of this repository

sites:
  - name: Landscapers Fortworth
    url: https://landscapersfortworth.com/
  - name: Landscapers Oakland
    url: https://landscapersoakland.com/
  - name: Audiohive
    url: https://audiohivetx.com/
  - name: Sound Phonic
    url: https://soundphonicca.com/
  - name: Bitztream
    url: https://bitztreamnc.com/
  - name: Audio Rific
    url: https://audiorificma.com/
  - name: Boosted Audio
    url: https://boostedaudioor.com/
  - name: Audio Watch
    url: https://audiowatchor.com/
  - name: Meat Market Phoenix
    url: https://meatmarketphoenix.com/
  - name: Steel Cradle Phoenix
    url: https://steelcradlephoenix.com/
  - name: Restorativ Phoenix
    url: https://restorativ-phoenix.com/
  - name: House Glitz Nashville
    url: https://houseglitznashville.com/
  - name: Flagstone Santa Ana
    url: https://flagstonesantaana.com/
  - name: Rock Rough Phoenix
    url: https://rockroughphoenix.com/
  - name: Gooyer Well Repairs
    url: https://gooyerwellrepairsomaha.com/
  - name: Fenrails Tampa
    url: https://fenrails-tampa.com/
  - name: Ace Windows Henderson
    url: https://acewindowshenderson.com/
  - name: Fortres Doors Oakland
    url: https://fortressdoorsoakland.com/
  - name: Bugbuster Austin
    url: https://bugbusteraustin.com/
  - name: The Flooring Guys Phoenix
    url: https://theflooringguysphoenix.com/
  
  - name: Advise Pilot Cincinnati
    url: https://advisepilotcincinnati.com/
  - name: Audio Key Kansas
    url: https://audiokeykansas.com/
  - name: Audio Loom Sandiego
    url: https://audioloomsandiego.com/
  - name: Cinematron Los Angeles
    url: https://cinematronlosangeles.com/
  - name: Landary Charlotte
    url: https://landarycharlotte.com/
  - name: Masonly Stockton
    url: https://masonlystockton.com/
  - name: Staff Mobile Cincinnati
    url: https://staffmobilecincinnati.com/
  - name: Steel Croft Phoenix
    url: https://steelcroftphoenix.com/
  - name: Telephoniq Las Vegas
    url: https://telephoniqlasvegas.com/
  - name: Translatium Houston
    url: https://translatium-houston.com/
    
  - name: Martinez Garcia Law
    url: https://martinezgarcialawmiami.com/
  - name: Class Deck Miami
    url: https://classdeckmiami.com/
  - name: Local Arquitectos Miami
    url: https://localarquitectosmiami.com/
  - name: Notario Publico San Antonio
    url: https://notariopublicosanantonio.com/
  - name: Ingles Genie San Antonio
    url: https://inglesgeniesanantonio.com/
  - name: Arquitecto San Antonio
    url: https://arquitectosanantonio.com/
  - name: English Mill Phoenix
    url: https://englishmillphoenix.com/
  - name: Arquitecto Phoenix
    url: https://arquitectophoenix.com/
  - name: Arquitecto Houston
    url: https://arquitectohouston.com/
  - name: Lab Fluent Houston
    url: https://labfluenthouston.com/
    
  - name: Cinemusbend
    url: https://cinemusbend.com/  
  - name: Real Time Digital Kansas
    url: https://realtimedigitalkansas.com/    
  - name: Willar Translation Tampa
    url: https://willartranslationtampa.com/
  - name: Tidy Culture Mesa
    url: https://tidyculturemesa.com/
  - name: Phone Bolt Colorado
    url: https://phoneboltcolorado.com/
  - name: Phone Start Systems
    url: https://phonestartsystems.com/
  - name: Welly Repairs
    url: https://wellyrepairs.com/    
  - name: Home Flix Chill
    url: https://homeflixchill.com/
  - name: Steel Grade Tusk
    url: https://steelgradetusk.com/
  - name: Miami Home Cinema
    url: https://miamihomecinema.com/
  - name: Floor Bright Cleaning
    url: https://floorbrightcleaning.com/
  - name: Accel Translate
    url: https://accel-translate.com/

  - name: Grand Tunity 
    url: https://grandtunity.com/ 
  - name: Piano Precision 
    url: https://piano-precision.com/ 
  - name: Syncphony Seattle 
    url: https://syncphonyseattle.com/ 
  - name: Seattle Magnitune 
    url: https://seattlemagnitune.com/ 
  - name: Key Tuning Seattle 
    url: https://keytuningseattle.com/ 
  - name: Lawn Workx 
    url: https://lawnworkx.com/
  - name: Green Turf Professionals 
    url: https://greenturfprofessionals.com/
  - name: Tree and Lawn 
    url: https://treeandlawnco.com/
  - name: Garden View Landscapers 
    url: https://gardenviewlandscapers.com/
  - name: Green View AZ 
    url: https://greenviewaz.com/
  - name: Landscape Topia 
    url: https://landscape-topia.com/ 
  - name: Giveme Green 
    url: https://giveme-green.com/ 
  - name: Decor and Scape 
    url: https://decorandscape.com/ 
  - name: The Great Gardens 
    url: https://thegreatgardens.com/ 
  - name: Environ Work 
    url: https://environwork.com/ 
  - name: Concrete Tree 
    url: https://concretetree.com/ 
  - name: Bricktically 
    url: https://bricktically.com/ 
  - name: Selective Concrete 
    url: https://selectiveconcrete.com/ 
  - name: Hard Stack Pro 
    url: https://hardstackpro.com/ 
  - name: Concrete Elementz 
    url: https://concreteelementz.com/ 
  - name: AZ Brick Frames 
    url: https://azbrickframes.com/ 
  - name: Concrete Connected 
    url: https://concrete-connected.com/ 
  - name: Brick Zone Works 
    url: https://brickzoneworks.com/ 
  - name: Superior Surface 
    url: https://superior-surface.com/ 
  - name: Rigid Ground Work 
    url: https://rigidgroundwork.com/ 
  - name: The AZ Clean Expert 
    url: https://theazcleanexpert.com/ 
  - name: The Weekly Squeaky Clean 
    url: https://theweeklysqueakyclean.com/ 
  - name: Sensitive Clean 
    url: https://sensitive-clean.com/ 
  - name: Bring Back Clean 
    url: https://bringbackclean.com/ 
  - name: Scrubit Clean 
    url: https://scrubit-clean.com/ 
  - name: Is Green Scene  
    url: https://isgreen-scene.com/  
  - name: Absolute Landscape Solutions 
    url: https://absolutelandscapesolutions.com/
  - name: Blooming Pots Landscaping 
    url: https://bloomingpotslandscaping.com/
  - name: Alpha Landscaping 
    url: https://alpha-landscaping.com/
  - name: Earth Works Lawn Cares 
    url: https://earthworkslawncares.com/
    
  - name: Prism Carpet Cleaning 
    url: https://prismcarpetcleaningtx.com/  
  - name: Get Fence Lab 
    url: https://getfencelab.com/  
  - name: Precise Word AZ 
    url: https://precisewordaz.com/  
  - name: Wellspring Tampa 
    url: https://wellspringtampa.com/   
  - name: Tidy Helpers CA 
    url: https://tidyhelpersca.com/  
  - name: Cleanaholic 
    url: https://cleanaholictn.com/  
  - name: Tidy Cleaners 
    url: https://tidycleanerstx.com/  
  - name: Cleanary Sandiego 
    url: https://cleanarysandiego.com/  
  - name: Cleanwagon Ohio 
    url: https://cleanwagonohio.com/  
  - name: Cleanasium  
    url: https://cleanasium.com/  
  - name: Scrub Clean Seattle 
    url: https://scrubcleanseattle.com/  
  - name: Clean Standards 
    url: https://clean-standards.com/  
  - name: Clean Wise  
    url: https://cleanwisenv.com/  
  - name: Tidy Train Cleaners 
    url: https://tidytraincleaners.com/  
  - name: Clean Kind  
    url: https://cleankindphx.com/   
  - name: Dragues Well Repair 
    url: https://dragueswellrepair.com/  
  - name: Well Repairman 
    url: https://wellrepairman.com/   
  - name: Agati Well Repairs 
    url: https://agatiwellrepairs.com/  
  - name: Sprint Fence 
    url: https://sprintfence.com/  
  - name: The Iron and Wood 
    url: https://theironandwood.com/  
  - name: Garden Gate Fence 
    url: https://gardengate-fence.com/  
  - name: Brickyard Fence 
    url: https://brickyardfence.com/ 
  - name: Cedar Built Floors 
    url: https://cedarbuiltfloors.com/
  - name: Jacobs Floors 
    url: https://jacobsfloorstx.com/
  - name: Hammond Floors 
    url: https://hammondfloors.com/
  - name: Patio Pros Elpaso 
    url: https://patioproselpaso.com/
  - name: Boon Wood Flooring 
    url: https://boonwoodflooring.com/
  - name: Pestero Bug Fortworth 
    url: https://pesterobugfortworth.com/
  - name: Bugmode Pest Control 
    url: https://bugmodepestcontrol.com/
  - name: Pest Busters 
    url: https://pestbustersnc.com/ 
  - name: Crycket Pest Control 
    url: https://crycketpestcontrol.com/
  - name: Pest Scout Pros 
    url: https://pestscoutpros.com/
  - name: Carpetomatic 
    url: https://carpetomatic.com/
  - name: Cleanaroo 
    url: https://cleanaroonv.com/ 
  - name: Scrubble Carpet Cleaners 
    url: https://srubblecarpetcleaners.com/
  - name: True Word Translation 
    url: https://truewordtranslation.com/
  - name: Global Translation 
    url: https://globaltranslationsrvs.com/
  - name: Simply Fluent 
    url: https://simply-fluent.com/
  - name: Catranslation Pros 
    url: http://catranslationpros.com/
  - name: Thrive Translation 
    url: http://thrivetranslation.com/
  - name: Marble Wood 
    url: https://marblewoodca.com/
  - name: Fresh Auto 
    url: https://fresh-auto.com/
  - name: Shiny Car Clean 
    url: https://shinycarclean.com/
  - name: Arborcare Ohio 
    url: https://arborcareohio.com/
  - name: Everlast Deck 
    url: https://everlastdeck.com/ 
  - name: My Drywall Guy 
    url: https://my-drywall-guy.com/ 
  - name: Speedy Drywall 
    url: https://speedy-drywall.com/ 
  - name: Mr Drywall TX 
    url: https://mrdrywalltx.com/
  - name: Wall Doctor Denver 
    url: https://walldoctordenver.com/ 
  - name: Speedy Auto Clean 
    url: https://speedyautoclean.com/     

  - name: Luxen Works 
    url: https://luxenworks.com/
  - name: Childrens Care AZ Website 
    url: http://childrenscareaz.org/   
  - name: Childrens Care AZ Backend 
    url: https://dev.childrenscareaz.org/   
  - name: Task Take Out 
    url: https://tasktakeout.com/
  - name: Palm Valley Montessori 
    url: https://palmvalleymontessori.com/   
  - name: Golferzen 
    url: https://golferzen.com/ 
  - name: Symplemarket 
    url: https://symplemarket.com/
  - name: GMB Power 
    url: https://gmbpower.com/     
  - name: Postcard Payments 
    url: https://postcardpayments.com/   
  - name: Just Retribution  
    url: https://justretribution.com/   
  - name: Symple Market US
    url: https://symplemarket.us/    
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upsite
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upsite
  introTitle: "**Upsite** is the open-source uptime monitor and status page of Symple Market, powered entirely by GitHub."
  introMessage: This is the status page which uses **real-time** data from [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
#  customBodyHtml: "<h1>Monitored Websites : </h1>"
#  js: "$(function() { console.log( 'ready!' ); });"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
